import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import UserProvider from "@/context/UserContext";
import Toast from "@/components/Toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Documents Manager",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=4"],
    apple: ["/apple-touch-icon.png?v=4"],
    shortcut: ["/apple-touch-icon.png"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <Navbar />
          <Toast />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
